### ISSUE TITLE
Implement (***), (&&&) for Strong and (+++) and (|||) for Choice

### ISSUE THREAD

**Issue by marcosh** [ekmett/profunctors#104]
Would it make sense to add implementations for `(***)` and `(&&&)` for a `Strong` profunctor when it is also a `Category`, similarly to what [Purescript does](https://pursuit.purescript.org/packages/purescript-profunctor/6.0.0/docs/Data.Profunctor.Strong)?

Similarly `(+++)` and `(|||)` could be added for `Choice`, when it is also a `Category`

**Comment by RyanGlScott** [comment]
Just to make sure that I understand correctly, are you proposing to add top-level functions with the same type signatures as `splitStrong` and `fanout`? Or are you proposing something else?

**Comment by marcosh** [comment]
yes, I would like to add to the library the following functions:

```haskell
(***) :: (Category p, Strong p) => p a b -> p c d -> p (a, c) (b, d)

(&&&) :: (Category p, Strong g) => p a b -> p a c -> p a (b, c)

(+++) :: (Category p, Choice p) => p a b -> p c d -> p (Either a c) (Either b d)

(|||) :: (Category p, Choice p) => p a c -> p b c -> p (Either a b) c
```

**Comment by RyanGlScott** [comment]
I'm not sure how I feel about giving them the same names as `Arrow`'s class methods, as that could possibly be confusing. I think I would prefer explicit names, such as the ones that `purescript` uses. Otherwise, I have no objection to adding these.

**Comment by marcosh** [comment]
agreed that the naming could be confusing. I'll create a PR with explicit names

**Comment by RyanGlScott** [comment]
Ouch, good catch. I wasn't aware of these potential pitfalls when I landed this.

We are fortunate in that these functions have not yet appeared in a Hackage release, so we are free to alter or remove these functions as we see fit. I'd be fine with either option. Which would you prefer?

**Comment by marcosh** [comment]
Personally, I'd like to keep them (and this is not surprising since I was the one who proposed and implemented this 😁 ).

I must admin that I'm not sure I understand the issue here. I don't see why we need to worry about `Arrow` at all. My PR introduces functions which have functionalities similar to some other functions present in `Arrow`, but are not at all related to them. They are just helper functions to work with choice or strong profunctors which are also categories.

Another option is just clarifying with an extended comment saying that it could happen that a type can have lawful instances for Category and Strong but not Arrow.

**Comment by marcosh** [comment]
> While it's true that `splitStrong` and friends are distinct from `Arrow`, the Haddocks do strongly imply that they are at least conceptually similar:
> 
> [profunctors/src/Data/Profunctor/Strong.hs](https://github.com/ekmett/profunctors/blob/05bd536a8e7e8299fd8320355cc4b6b816e07df8/src/Data/Profunctor/Strong.hs#L114)
> 
> Line 114 in [05bd536](/ekmett/profunctors/commit/05bd536a8e7e8299fd8320355cc4b6b816e07df8)
>  -- `splitStrong` is analogous to `Control.Arrow.***`. 
> 
> Based on this information, I think it's possible that one might be tempted to implement `(***) = splitStrong`. At the very least, I think it would be worth including a disclaimer in the Haddocks that `splitStrong` may not give rise to a lawful `Arrow` instance (and perhaps include a counterexample).

I'll create a new PR clarifying the comment, explaining the situation and providing a link to the posts shared by @Topsii

**Comment by Topsii** [comment]
Thank you for minding my concerns on an already closed issue! 😮

The original paper _Generalising monads to arrows_ states

> The reader may also wonder why we chose to take `first` as primitive, rather than
(say) `&&&` which resembles a well-known categorical operator. There are two main
reasons for our choice
> - Firstly, since in general our arrows represent computations with effects, evaluation
order makes a difference. The definition of `f &&& g` above is explicit about this: the
effects of `f` are composed with the effects of `g` in that order, that is evaluation
is left to right. The definitions of `&&&` and `∗∗∗` above can be used as algebraic laws
by the programmer, laws which capture evaluation order. In contrast, had we taken
`&&&` as primitive, then the designer of each arrow-based library would have had to
choose either left-to-right or right-to-left evaluation, with the result that evaluation
order would probably differ from case to case. This would make the behaviour of
arrow-based libraries less predictable, and reduce the number of useful laws that
arrow combinators satisfy.
> - Secondly, ...

For Arrows there is _no_ law that
```
first f >>> second g = second g >>> first f
```
According to the paper:
> We have to require that the function be pure, to avoid potentially
changing the order in which side-effects occur. Thus the law becomes
> ```
> first f >>> second (arr g) = second (arr g) >>> first f
> ```
Since you are drawing the comparison with `Arrow` in the documentation, I wonder whether it should be
```haskell
splitStrong l r = second' r . first' l
-- instead of
splitStrong l r = first' l . second' r

--and likewise
splitChoice l r = right' r . left' l
-- instead of
splitChoice l r = left' l . right' r
```
Or the documentation could mention the order, in which any side-effects will occur.

The side-effect order given for `&&&` in the paper seems related to the pervasive use of `>>>` in the paper (or when using Arrows in general?). There are other settings with a pervasive use of `(.)` and `<<<`  combinators instead of `>>>`.

Unfortunately, the documentation of the Arrow class is already not great. This explanation of the law is buried in a paper that is indirectly linked to at the top of the module's documentation. Likewise, the documentation does not prominently mention the order of side-effects for, e.g. `&&&`. 

I don't have any stakes in this, but I thought I should rather bring it up than not.

Also, I am curious to see a use case for `splitStrong`, `fanOut`, `splitChoice` or `fanIn`.
I assume it involves a data type that has Category and Strong/Choice instances but admits no Arrow instance or only a less performant one. But no such type comes to mind. Perhaps, it will convince me that  `(***)`, `(&&&)`, `(+++)` and `(|||) ` do not suffice and these functions should exist 😅.  I hope I was able to convey my issues with them. Potentially, a use case could be insightful for readers of the documentation too.

Again, thank you for taking action so promptly!
